name: whatsapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  uuid: ^4.5.1
  fluttertoast: ^8.2.12
  intl: ^0.19.0
  flutter_contacts: ^1.1.9+2
  image_picker: 1.1.2
  file_picker: ^10.1.9
  video_player: ^2.8.2
  firebase_storage: ^12.4.5
  flutter_pin_code_fields: ^2.1.0
  country_picker: ^2.0.20
  cached_network_image: ^3.3.1
  country_pickers: ^3.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^8.0.3
  font_awesome_flutter: ^10.8.0
  get_time_ago: ^2.3.1
  swipe_to: ^1.0.2
  emoji_picker_flutter: ^4.3.0
  giphy_picker: ^3.0.1
  flutter_sound: ^9.2.13
  path_provider: ^2.0.14
  audioplayers: ^6.4.0
  just_audio: ^0.10.2
  flutter_story_view: 0.0.4
  # flutter_contacts_service: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
